version: "3.2"
services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
  flask-simple:
    build:
      dockerfile: Dockerfile1
      context: .
    command: python task6.py
    volumes:
      - ./src:/usr/src/app/
      
  mongodb:
    image: mongo
    ports:
      - 27018:27017
      